Website/Library/urls.py
from django.urls import path

from . import views

app_name = 'Library'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('library/', views.BookListView.as_view(), name='book_list'),
    path('library/<int:pk>/', views.BookDetailView.as_view(), name='book_detail'),
    path('library/import/', views.ImportView.as_view(), name='import'),
    path('library/import_book/', views.import_book, name='importer')
]

Website/Website/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Library.urls')),
]

Website/Library/models.py
from django.db import models
import json


class Book(models.Model):
    isbn = models.IntegerField()
    title = models.CharField(max_length=200)
    author = models.CharField(max_length=200)
    data_url = models.CharField(max_length=200, null=True)
    cover_url = models.CharField(max_length=300, null=True)

    import_date = models.DateTimeField('date added', null=True)
    is_in_stock = models.BooleanField(default=True)
    quantity = models.IntegerField(default=0)

Website/Library/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.http import HttpResponseRedirect, HttpResponse, request
from django.utils import timezone
from django.urls import reverse
from django.shortcuts import redirect
from . import services
import requests
from .models import Book
import json
# Create your views here.


class HomeView(generic.TemplateView):
    template_name = 'Library/home.html'


# Add books to library using ISBN number
def import_book(request):
    isbn = request.POST['isbn_box']
    # add imported book to database unless already there
    book, created = Book.objects.get_or_create(isbn=isbn)
    book_data = services.get_book(isbn)
    book.title = book_data["title"]
    book.author = services.get_author_name(book_data["authors"][0]["key"])
    book.data_url = "https://openlibrary.org/isbn/" + str(isbn)
    book.cover_url = "https://covers.openlibrary.org/b/id/" + str(book_data["covers"][0]) + "-L.jpg"
    book.import_date = timezone.now()
    book.quantity += 1
    book.save()
    # redirect_url = 'Library/book_detail/' + str(book.pk)
    return HttpResponseRedirect(reverse('Library:book_detail', args=(book.pk,)))


class ImportView(generic.TemplateView):
    template_name = 'Library/import.html'

    """
    def get_book_details(self):
        url = "https://openlibrary.org/isbn/9780446310789.json"
        # params = {'publishers': publishers}
        response = requests.get(url).json()
        # book_dict = {'response': response}
        return render(request, 'Library/import.html', {'response': response})
    """


# Display a list of my books
class BookListView(generic.ListView):
    # ListView generic view uses a default template called
    # <app name>/<model name>_list.html; we use template_name to tell ListView
    # to use our existing "Library/books_list.html" template.
    template_name = 'Library/book_list.html'
    context_object_name = 'latest_books_list'

    def get_queryset(self):
        # Return the 10 most recently added books.
        # Book.objects.filter(import_date__lte=timezone.now()) returns a queryset
        # containing Books whose add_date is earlier than or equal to timezone.now().
        return Book.objects.filter(import_date__lte=timezone.now()).order_by('-import_date')[:10]



class BookDetailView(generic.DetailView):
    model = Book
    template_name = 'Library/book_detail.html'


    #def get_book_details(year, author):

Website/Library/templates/Library/book_detail.html
<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
        <title>ReReads: Home</title>

        <!-- Nav bar using .nav (nav-tabs>Fill and Justify)-->
        <div class="p-3 mb-2 bg-tabs text-white">
            <ul class="nav nav-tabs justify-content-end">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Library:home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Library:book_list' %}">Library</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Library:import' %}">Book Importer</a>
                </li>
            </ul>
        </div>
    </head>

    <body>
        <div class="container">
            <div class="row">
                <div class="col-4">
                    <img src={{ book.cover_url }} class="img-thumbnail" alt="Book cover" height="250">
                </div>
                <div class="col">
                    <h2>{{book.title}}</h2>
                    <h3>Author: {{book.author}}</h3>
                    <h6>ISBN: {{book.isbn}}</h6>
                    <h6>Import date: {{book.import_date}}</h6>
                    <br>
                    <h4>Items in stock: {{book.quantity}}</h4>
                    <a href={{ book.data_url }}>View in OpenLibrary</a>
                </div>
            </div>
        </div>
    </body>
</html>

Website/Library/templates/Library/book_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

    <title>ReReads: Library</title>

    <!-- Nav bar using .nav (nav-tabs>Fill and Justify)-->
    <div class="p-3 mb-2 bg-light text-white">
        <ul class="nav nav-tabs justify-content-end">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'Library:home' %}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" href="{% url 'Library:book_list' %}">Library</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'Library:import' %}">Book Importer</a>
            </li>
        </ul>
    </div>
</head>

<body>
    {% if latest_books_list %}
    <h3>These are the books currently available in the library.</h3>
    <ul>
        {% for book in latest_books_list %}
            <li><a href = "{% url 'Library:book_detail' book.id %}">{{book.title}}</a>  (In stock: {{book.quantity}})</li>
        {% endfor %}
    </ul>
    {% else %}
        <p>No books in stock currently.</p>
    {% endif %}
</body>
</html>

Website/Library/templates/Library/home.html
<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
        <title>ReReads: Home</title>

        <!-- Nav bar using .nav (nav-tabs>Fill and Justify)-->
        <div class="p-3 mb-2 bg-light text-white">
            <ul class="nav nav-tabs justify-content-end">
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'Library:home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Library:book_list' %}">Library</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Library:import' %}">Book Importer</a>
                </li>
            </ul>
        </div>
    </head>
    <body>
        <h1>Welcome to ReReads!</h1>
        <h3>The site to locate second-hand books in Cape Town</h3>
        <br>
        <h5>If you're looking for a book, check out our Library tab to see what is in stock.<br>If you're a vendor and want to list a book on our site, head to the Book importer.</h5>
    </body>
</html>

Website/Library/templates/Library/import.html
<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
        <title>ReReads: Import</title>

        <!-- Nav bar using .nav (nav-tabs>Fill and Justify)-->
        <div class="p-3 mb-2 bg-light text-white">
            <ul class="nav nav-tabs justify-content-end">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Library:home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Library:book_list' %}">Library</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'Library:import' %}">Book Importer</a>
                </li>
            </ul>
        </div>
    </head>
    <body>
        <h1>Library book importer</h1>
        <form action="{% url 'Library:importer' %}" method="post">
        {% csrf_token %}
            <label for="isbn_box">Search with ISBN: </label>
            <input type="text" id="isbn_box" name="isbn_box">
            <input type="submit" value="Import book"><br>
        </form>
    </body>
</html>